name: Hello World CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
