name: C++ CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Clang
      run: sudo apt-get install -y clang-format
    
    - name: Format code
      run: find . -name solutions -prune -o -name '*.cpp' -print0 | xargs -0 clang-format -i && git diff --exit-code

    - name: Set up Cmake
      run: sudo apt-get install -y cmake

    - name: Install Google Test
      run: sudo apt-get install -y libgtest-dev

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./tests

